name: .NET Core

on: [push]

permissions:
  id-token: write
  contents: read

env:
  AZURE_WEBAPP_NAME: asp-cookmartin
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '10.0.x'
  CSPROJ: 'CookMartin.API/CookMartin.API.csproj'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repo
      - uses: actions/checkout@main
      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{env.DOTNET_VERSION}}

      # Run dotnet build and publish
      - name: dotnet build and publish
        run: |
          dotnet restore ${{CSPROJ}}
          dotnet build ${{CSPROJ}} -c Release
          dotnet publish ${{CSPROJ}} -c Release --output ${{ github.workspace}}/publish

      - name: Verify publish output
        run: |
          ls -la ${{ github.workspace }}/publish
          find ${{ github.workspace }}/publich -maxdepth 2 -type f | head -n 50

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: '${{ github.workspace }}/publish'

      - name: logout
        run: |
          az logout
